services:
  3d-printing-business:
    image: zzz12929/3d-printing-business:latest
    container_name: 3d-printing-business
    restart: unless-stopped
    ports:
      - "12929:12929"
    volumes:
      - 3d-printing-business-data:/data

volumes:
  3d-printing-business-data:
